services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  app:
    build: .
    container_name: node-app
    restart: always
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGHOST: postgres
      PGPORT: 5432
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres

    networks:
      - app-network
    volumes:
      - .:/usr/src/app
    command: sh -c "until pg_isready -h $PGHOST -p $PGPORT; do echo 'Waiting for PostgreSQL...'; sleep 1; done && npm start" # waiting for postgre container

volumes:
  postgres_data:

networks:
  app-network: