name: CI with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Build and Start Backend with Docker Compose
        working-directory: ./backend
        run: |
          docker compose up --build -d

      - name: Install Frontend Dependencies and Start
        working-directory: ./frontend
        run: |
          npm install
          npm start
